#!/bin/sh
xrdb -load ~/.Xdefaults &

# Synchronize X clipboard and X selection.
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Autostart
kbdd &
nm-applet &
thunderbird &
firefox &
xscreensaver -no-splash &
start-pulseaudio-x11 &
dropbox &
SpiderOakONE &
wmname LG3D &
kupfer &
rsibreak &

# UIM related
# export GTK_IM_MODULE='uim'
# export QT_IM_MODULE='uim'
# uim-xim &
# export XMODIFIERS=@im='uim'
# uim-toolbar-gtk-systray &
export TERMINAL="terminology"

exec i3 -V >> ~/.config/i3/i3log 2>&1
