#!/bin/sh
xrdb -load ~/.Xdefaults &

firefox &
nm-applet &
kbdd &
xscreensaver -no-splash &
rsibreak &

# Host-specific autostart and overrides.
if [ -f ~/.xinitrc_host_specific ]; then
  . ~/.xinitrc_host_specific
fi

# UIM related
# export GTK_IM_MODULE='uim'
# export QT_IM_MODULE='uim'
# uim-xim &
# export XMODIFIERS=@im='uim'
# uim-toolbar-gtk-systray &
export XDG_CURRENT_DESKTOP="i3"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3 --shmlog-size=26214400
