Plug 'tpope/vim-bundler'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-rake'
Plug 'neovimhaskell/haskell-vim'
Plug 'ujihisa/neco-ghc'
Plug 'hspec/hspec.vim'
Plug 'xolox/vim-misc' | Plug 'linduxed/vim-lua-ftplugin'
Plug 'leafo/moonscript-vim'
Plug 'kchmck/vim-coffee-script'
