#!/usr/bin/env ruby

require 'English'

exit 0 if ARGV.include?('--no-verify')

keywords = %w(binding.pry console.log)

files_changed = `git diff-index --name-only HEAD --`.split

exit 0 if files_changed.empty?

`git grep -q -E "#{keywords.join('|')}" #{files_changed.join(' ')}`

if $CHILD_STATUS.exitstatus.zero?
  puts '# Check following lines:'
  files_changed.each do |file|
    keywords.each do |keyword|
      `git grep -q #{keyword} #{file}`
      if $CHILD_STATUS.exitstatus.zero?
        line = `git grep -n #{keyword} #{file} | awk -F ":" '{print $2}'`.split.join(', ')
        puts "#\t\033[31m#{file}\033[0m contains #{keyword} at line \033[33m#{line}\033[0m."
      end
    end
  end
  exit 1
end
