Plug 'elixir-lang/vim-elixir'
Plug 'awetzel/elixir.nvim', { 'do': 'yes \| ./install.sh' }
Plug 'kchmck/vim-coffee-script'
Plug 'mustache/vim-mustache-handlebars'
Plug 'vim-scripts/octave.vim'
Plug 'rust-lang/rust.vim'
Plug 'racer-rust/vim-racer'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-rake'
Plug 'neovimhaskell/haskell-vim'
Plug 'ujihisa/neco-ghc'
Plug 'hspec/hspec.vim'
Plug 'vim-scripts/warsow.vim'
Plug 'wlangstroth/vim-racket'
