[theme]
theme = "space-villain"
[icons]
icons = "awesome4"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = " $icon $used/$total ($available.eng(w:2) free)"
alert_unit = "GB"
alert = 190
warning = 210

[[block]]
block = "memory"
format = " $icon $mem_used/$mem_total($mem_total_used_percents.eng(w:2))"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
format = "KB: $layout"

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4)"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization"

[[block]]
block = "temperature"
format = " $icon max: $max $icon avg: $average"

[[block]]
block = "nvidia_gpu"
format = " $icon $utilization $memory $temperature"
interval = 1

# [[block]]
# block = "pacman"
# interval = 43200
# format = "$pacman + $aur = $both updates available"
# format_singular = "$both update available"
# format_up_to_date = "system up to date"
# critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command = "yay -Qua"

[[block]]
block = "net"
device = "wlp4s0"
format = " $icon $speed_down"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%a %-d %b %X W%V')"
