#!/bin/sh
xrdb -load ~/.Xdefaults &

# Synchronize X clipboard and X selection.
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Autostart
[ ! -s ~/.mpd/pid  ] && mpd &
kbdd &
wicd-gtk -t &
thunderbird &
firefox &
xscreensaver -no-splash &
start-pulseaudio-x11 &
dropboxd &
SpiderOak &
wmname LG3D &
kupfer &
workrave &

# UIM related
# export GTK_IM_MODULE='uim'
# export QT_IM_MODULE='uim'
# uim-xim &
# export XMODIFIERS=@im='uim'
# uim-toolbar-gtk-systray &
export TERMINAL="roxterm"

exec i3 -V >> ~/.config/i3/i3log 2>&1
