#!/bin/sh
xrdb -load ~/.Xdefaults &

# Autostart
kbdd &
nm-applet &
firefox &
start-pulseaudio-x11 &
SpiderOakONE &
kupfer &
rsibreak &
xrandr --output DP-0 --mode 2560x1440 --rate 144 &
xrandr --output DP-2 --mode 3840x2160 --pos 2560x-720 &
xscreensaver -no-splash &
redshift-gtk &
flameshot &
lxsession &
1password &

# UIM related
# export GTK_IM_MODULE='uim'
# export QT_IM_MODULE='uim'
# uim-xim &
# export XMODIFIERS=@im='uim'
# uim-toolbar-gtk-systray &
export TERMINAL="kitty"
export QT_STYLE_OVERRIDE="kvantum-dark"
export XDG_CURRENT_DESKTOP="i3"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3 -V >> ~/.config/i3/i3log 2>&1
