#!/bin/sh
xrdb -load ~/.Xdefaults &

# Synchronize X clipboard and X selection.
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Autostart
[ ! -s ~/.mpd/pid  ] && mpd &
kbdd &
nm-applet &
thunderbird &
firefox &
start-pulseaudio-x11 &
dropbox &
SpiderOakONE &
wmname LG3D &
kupfer &
workrave &
xrandr --output HDMI-0 --mode 1920x1080 --right-of DP-0 --rotate left &
xscreensaver -no-splash &
redshift-gtk &

# UIM related
# export GTK_IM_MODULE='uim'
# export QT_IM_MODULE='uim'
# uim-xim &
# export XMODIFIERS=@im='uim'
# uim-toolbar-gtk-systray &
export TERMINAL="roxterm"

exec i3 -V >> ~/.config/i3/i3log 2>&1
