#!/bin/sh
xrdb -load ~/.Xdefaults &

# Synchronize X clipboard and X selection.
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Autostart
kbdd &
nm-applet &
thunderbird &
firefox &
start-pulseaudio-x11 &
SpiderOakONE &
wmname LG3D &
kupfer &
rsibreak &
xrandr --output DP-0 --mode 2560x1440 --rate 144 &
xrandr --output DP-2 --mode 3840x2160 --pos 2560x-720 &
xscreensaver -no-splash &
redshift-gtk &

# UIM related
# export GTK_IM_MODULE='uim'
# export QT_IM_MODULE='uim'
# uim-xim &
# export XMODIFIERS=@im='uim'
# uim-toolbar-gtk-systray &
export TERMINAL="xfce4-terminal"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3 -V >> ~/.config/i3/i3log 2>&1
