# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export XDG_CONFIG_HOME="$HOME/.config/"

#
# Editors
#
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Less
#
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -i -M -R -S -w -X -z-4'
export LESSHISTFILE="-"

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Paths
#
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Add place for custom functions (e.g. completion).
fpath=(
  $HOME/.zsh/functions
  $fpath
)

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.asdf/shims
  $HOME/.local/bin
  $HOME/.cabal/bin
  $HOME/bin
  /usr/local/{bin,sbin}
  /usr/bin/{vendor_perl,site_perl,core_perl}
  /usr/{bin,sbin}
  /{bin,sbin}
)

#
# Temporary Files
#
if [[ -d "$TMPDIR" ]]; then
  export TMPPREFIX="${TMPDIR%/}/zsh"
  if [[ ! -d "$TMPPREFIX" ]]; then
    mkdir -p "$TMPPREFIX"
  fi
fi
